### PR TITLE
Using ijson to load item by item, so it becomes easy to load with low RAM

### PR DESCRIPTION
**Pull request by SamimAB**
I was having trouble loading converting the dataset from JSON to tsv in Google Colab as it was running out of RAM. So I thought this might help if you don't have enough RAM as it loads the JSON one item at a time and writes to the output tsv file line by line.

### CODE REVIEW

**Comment by Sypherd** [comment]
Did you close this because there was no response? I think it's a valuable addition, I also had to leverage `ijson` to convert it due to OOM.

**Comment by SamimAB** [comment]
Yeah, I closed the commit because there was no response. I am very new to contributions to git so I dont know the etiquettes 
very well or would it be proper to keep it open. In fact this was my first contribution. I'm glad to hear that you find it valuable. I really appreciate your feedback. If there's interest in integrating this, I'd be more than happy to reopen the commit or submit a new one. Please let me know how you'd like to proceed.

**Comment by Sypherd** [comment]
That's a great first contribution! Most people start with fixing typos in a README but yours actually improves the repo without making unwanted functionality changes. I'm not a maintainer (although I have asked to be added as one) but I think this is definitely something that should get merged. I also have this implemented locally so it would be good to help others get started as well without having to work around this. I'd recommend reopening it and reaching out to someone on the Discord.

**Comment by SamimAB** [comment]
Thank you for the encouragement. I will do just that.

**Pull request closed without merging**
